name: Build Node binaries for macOS (arm64)

on:
  workflow_dispatch:

jobs:
  macos-arm64:
    runs-on: macos-arm64

    defaults:
      run:
        shell: arch -arch arm64e bash -l -eo pipefail {0}

    strategy:
      fail-fast: false
      matrix:
        target-node: [14, 16, 18, 19]

    steps:
      - uses: actions/checkout@v2

      - run: yarn install

      - run: yarn start --node-range node${{ matrix.target-node }} --output dist

      - name: Check if binary is compiled
        id: check_file
        run: |
          (test -f dist/*.sha256sum && echo ::set-output name=EXISTS::true) || echo ::set-output name=EXISTS::false

      - uses: actions/upload-artifact@v2
        if: steps.check_file.outputs.EXISTS == 'true'
        with:
          name: node${{ matrix.target-node }}-macos-arm64
          path: dist/*
